name: dev-cicd-workflow.yml
on:
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_SCHEMA: ${{ secrets.DB_DEV_SCHEMA }}
      DB_USER: ${{ secrets.DB_USER }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - name: Rename jar to app.jar
        working-directory: build/libs
        run: |
          JAR_NAME=$(ls *.jar | head -n 1)
          mv "$JAR_NAME" app.jar

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: build/libs/app.jar

  deploy:
    name: Deploy on EC2 for dev
    needs: build
    runs-on: [ self-hosted, dev, Linux, ARM64 ]

    steps:
      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: ~/cake-reservation

      - name: Make deploy script executable
        run: chmod +x ~/cake-reservation/deploy.sh

      - name: Run deploy script with sudo
        run: sudo bash ~/cake-reservation/deploy.sh
